#ifndef SDP_RET_H
#define SDP_RET_H

typedef enum {
  SDP_RET_SUCCESS,
  SDP_RET_PARTIAL_SUCCESS,
  SDP_RET_PRIMAL_INFEASIBLE,
  SDP_RET_DUAL_INFEASIBLE,
  SDP_RET_NEAR_PRIMAL_INFEASIBLE,
  SDP_RET_NEAR_DUAL_INFEASIBLE,
  SDP_RET_MAX_ITER_REACHED,
  SDP_RET_LACK_OF_PROGRESS,
  SDP_RET_UNKNOWN
} sdp_ret_t;

#endif  /* SDP_RET_H */
